language: node_js
node_js:
- '6'
install: npm install
script: npm run test-babel
after_script:
- npm run coveralls
env:
  global:
    secure: GL3e5sOon2MpSRko0OOfxqZ2fj5uPd3MOBTiNbcIHh3CjL4xkwml9gUWnzHS+/TxmOKfpzj9drUSupSitqtsMpsYjNxoUIwKUBSj3rsHKfmei0j+RtpF246yGG8ODGoOar1uRpxXIN/AnBqdYpl5/F1lB1ctRkDYgRkARDrTtLHjmfcr0EyH/agrV7WzzJiAKflnE+kinXvoSK0fhjwozMGvvobUIe9yBuPEEHfMQ+dZODrhdfbFBNPq+lm0v6LunusfeVd3rTIIx8gqhVDRcX/2pWdsoo/kJAu2n6WRfxOB9sXu81Bn4WQ7cDL83azs/0oFRPZIJsQCAtUq3AjZvL7+dLmxUlMAnS0N1w5386X7tPkvHhoEYV7nmQGFuCBnWcV1+NykaoSaq0lkhJ0Y4gmbcjOoB4j7uZwVuUG2QCpAHDb83ColUCowtjg7Y9lgCWSwl/oA9bV/rEhrqpV9kZB01MUKqOnr4cz+svg1z4iQwm3Fo38I/rViOvJSnesAK0jrPXzEwft9D9PxkGF94lpGdS0ydP2YJuwegpANemOu5c90RzxDCQTAvO/MMuJ8zcKRac6DGt2lfh+SlgyJ24EQnpHn+UmCKxPk8nT5fYyXnhhuUaeUkFoBjLe7GG2Sm/LuvSSgi8cPyimoxs1t4yI2L9/4DLYZ8mT8w4ZeBy8=
